name: flutter_template

description: Template for developing an application in Flutter.

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animate_do: ^3.1.2
  animated_flip_counter: ^0.3.4
  animated_text_kit: ^4.2.2
  avatar_glow: ^3.0.1
  background_fetch: ^1.3.7
  bootstrap_icons: ^1.11.3
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  dart_phonetics: ^1.0.1
  dio: ^5.7.0
  dotted_line: ^3.2.3
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  expandable_page_view: ^1.0.17
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_launcher_icons: ^0.11.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.5
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.14
  flutter_web_plugins:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  gap: ^3.0.1
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  hidable: ^1.0.5
  hovering: ^1.0.4
  intl: ^0.19.0
  local_auth: ^2.1.7
  meta: ^1.15.0
  mockito: ^5.4.4
  pull_down_button: ^0.10.2
  qr_flutter: ^4.1.0
  responsive_builder: ^0.7.1
  riverpod_annotation: ^2.6.1
  nullable_absent: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.3.0
  integration_test:
    sdk: flutter
  riverpod_generator: ^2.6.3

# Run command to generate .gr file
# 1) flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/sh.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/sh.png"
  background_color_ios: "#000000"
  image_path_ios: "assets/images/sh.png"

# Run command to generate splash screen
# 1) flutter clean
# 2) flutter pub get
# 3) flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: '#ffffff'
  image: assets/images/logo.png
# background_image:src
# Configuración general de Flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
