name: taqueria_vargas

description: Template for developing an application in Flutter.

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animate_do: ^3.1.2
  animated_flip_counter: ^0.3.4
  animated_text_kit: ^4.2.2
  another_flushbar: ^1.12.30
  avatar_glow: ^3.0.1
  background_fetch: ^1.3.7
  bootstrap_icons: ^1.11.3
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  dart_phonetics: ^1.0.1
  dio: ^5.7.0
  dotted_line: ^3.2.3
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  expandable_page_view: ^1.0.17
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.5
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.14
  flutter_web_plugins:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  gap: ^3.0.1
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  hidable: ^1.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hovering: ^1.0.4
  intl: ^0.20.2
  local_auth: ^2.1.7
  meta: ^1.15.0
  mockito: ^5.4.4
  nullable_absent: ^2.0.0
  pull_down_button: ^0.10.2
  qr_flutter: ^4.1.0
  responsive_builder: ^0.7.1
  riverpod_annotation: ^2.6.1
  shimmer: ^3.0.0
  uuid: ^4.5.1
  dartz: ^0.10.1
  mobile_scanner: ^7.0.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.3.0
  hive_generator: ^2.0.1
  integration_test:
    sdk: flutter
  riverpod_generator: ^2.6.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_taqueria.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo_taqueria.png"
  background_color_ios: "#FFFFFF"
  image_path_ios: "assets/images/logo_taqueria.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
